// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEv78jeO-d4iKVbp0VqsfP9EbYl4ZF6_w',
    appId: '1:23945154491:web:35e5133215ed7491a5fe9e',
    messagingSenderId: '23945154491',
    projectId: 'fireauthentication-1b927',
    authDomain: 'fireauthentication-1b927.firebaseapp.com',
    storageBucket: 'fireauthentication-1b927.firebasestorage.app',
    measurementId: 'G-C45T3N78V7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOFCB2eacKlb-oMNiEkwPMAFdY04I1-QA',
    appId: '1:23945154491:android:79abd61b30701f54a5fe9e',
    messagingSenderId: '23945154491',
    projectId: 'fireauthentication-1b927',
    storageBucket: 'fireauthentication-1b927.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC69dHag_1-DKar3ySzH0fPyRaLbHSa0O8',
    appId: '1:23945154491:ios:b546a6aa901cb505a5fe9e',
    messagingSenderId: '23945154491',
    projectId: 'fireauthentication-1b927',
    storageBucket: 'fireauthentication-1b927.firebasestorage.app',
    iosBundleId: 'com.example.fireauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC69dHag_1-DKar3ySzH0fPyRaLbHSa0O8',
    appId: '1:23945154491:ios:b546a6aa901cb505a5fe9e',
    messagingSenderId: '23945154491',
    projectId: 'fireauthentication-1b927',
    storageBucket: 'fireauthentication-1b927.firebasestorage.app',
    iosBundleId: 'com.example.fireauth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEv78jeO-d4iKVbp0VqsfP9EbYl4ZF6_w',
    appId: '1:23945154491:web:0f9bb9ff8a0f0a47a5fe9e',
    messagingSenderId: '23945154491',
    projectId: 'fireauthentication-1b927',
    authDomain: 'fireauthentication-1b927.firebaseapp.com',
    storageBucket: 'fireauthentication-1b927.firebasestorage.app',
    measurementId: 'G-2LXDXQH00Q',
  );

}