import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:google_sign_in/google_sign_in.dart'; // REQUIRED: Add google_sign_in package locally
import 'firebase_options.dart'; // REQUIRED: This file is generated by 'flutterfire configure'

// ----------------------------------------------------------------------
// 1. AUTHENTICATION SERVICE (Logic Layer)
// ----------------------------------------------------------------------

class AuthService {
  final FirebaseAuth _auth = FirebaseAuth.instance;
  final GoogleSignIn _googleSignIn = GoogleSignIn();

  // Stream to monitor user authentication state (Auth Observer)
  Stream<User?> get authStateChanges => _auth.authStateChanges();

  // Sign In (Email/Password)
  Future<User?> signIn({required String email, required String password}) async {
    try {
      final userCredential = await _auth.signInWithEmailAndPassword(
          email: email, password: password);
      return userCredential.user;
    } on FirebaseAuthException catch (e) {
      throw _handleAuthError(e);
    }
  }

  // Sign Up (Email/Password)
  Future<User?> signUp({required String email, required String password}) async {
    try {
      if (password.length < 8) {
        throw const FormatException('Password must be at least 8 characters long.');
      }
      final userCredential = await _auth.createUserWithEmailAndPassword(
          email: email, password: password);
      return userCredential.user;
    } on FirebaseAuthException catch (e) {
      throw _handleAuthError(e);
    } on FormatException catch (e) {
      throw e.message;
    }
  }

  // Sign In with Google
  Future<User?> signInWithGoogle() async {
    try {
      final GoogleSignInAccount? googleUser = await _googleSignIn.signIn();

      if (googleUser == null) {
        return null; // User cancelled
      }

      final GoogleSignInAuthentication googleAuth = await googleUser.authentication;
      final AuthCredential credential = GoogleAuthProvider.credential(
        accessToken: googleAuth.accessToken,
        idToken: googleAuth.idToken,
      );

      final UserCredential userCredential =
      await _auth.signInWithCredential(credential);

      return userCredential.user;

    } on FirebaseAuthException catch (e) {
      throw _handleAuthError(e);
    } catch (e) {
      throw 'Google Sign-In failed: $e';
    }
  }


  // Sign Out
  Future<void> signOut() async {
    await _auth.signOut();
    // Also sign out from Google if signed in via Google
    if (await _googleSignIn.isSignedIn()) {
      await _googleSignIn.signOut();
    }
  }

  // Password Reset
  Future<void> sendPasswordReset({required String email}) async {
    try {
      await _auth.sendPasswordResetEmail(email: email);
    } on FirebaseAuthException catch (e) {
      throw _handleAuthError(e);
    }
  }

  // Helper function to map Firebase error codes to user-friendly messages
  String _handleAuthError(FirebaseAuthException e) {
    switch (e.code) {
      case 'user-not-found':
        return 'User not found.';
      case 'wrong-password':
        return 'Invalid password.';
      case 'invalid-email':
        return 'The email address is badly formatted.';
      case 'weak-password':
        return 'Password is too weak. Min 8 chars required.';
      case 'email-already-in-use':
        return 'An account already exists with that email.';
      case 'channel-error':
        return 'Invalid email or password.';
      case 'account-exists-with-different-credential':
        return 'This email is already registered with a different provider.';
      default:
        return 'Authentication failed: ${e.message}';
    }
  }
}

// ----------------------------------------------------------------------
// 2. MAIN APPLICATION AND WIDGETS
// ----------------------------------------------------------------------

// MANDATORY ASYNC MAIN FUNCTION FOR FIREBASE INIT
void main() async {
  // 1. Ensure the Flutter engine is initialized before calling native code (Firebase)
  WidgetsFlutterBinding.ensureInitialized();

  try {
    // 2. Initialize Firebase using the generated configuration options
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    // Handle initialization failure gracefully
    debugPrint("Firebase initialization failed: $e");
  }

  runApp(const AuthApp());
}

class AuthApp extends StatelessWidget {
  const AuthApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Firebase Auth',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.indigo,
        visualDensity: VisualDensity.adaptivePlatformDensity,
        inputDecorationTheme: InputDecorationTheme(
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(10.0),
            borderSide: BorderSide.none,
          ),
          filled: true,
          fillColor: Colors.indigo.shade50,
          contentPadding: const EdgeInsets.symmetric(vertical: 16.0, horizontal: 20.0),
        ),
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            backgroundColor: Colors.indigo.shade600,
            foregroundColor: Colors.white,
            padding: const EdgeInsets.symmetric(vertical: 16),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(10),
            ),
            elevation: 5,
          ),
        ),
      ),
      home: const AuthWrapper(),
    );
  }
}

/**
 * Auth Observer and Routing Guard
 * Uses StreamBuilder on authStateChanges to manage navigation state.
 */
class AuthWrapper extends StatelessWidget {
  const AuthWrapper({super.key});

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: AuthService().authStateChanges,
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            body: Center(child: CircularProgressIndicator()),
          );
        }

        final user = snapshot.data;

        // Screen Guard Logic: If user is null, show AuthStack (WelcomeScreen)
        if (user == null) {
          return const WelcomeScreen();
        } else {
          // If user exists, show AppStack (HomeScreen)
          return const HomeScreen();
        }
      },
    );
  }
}

// ----------------------------------------------------------------------
// 3. AUTH STACK SCREENS (Login/Signup/Welcome)
// ----------------------------------------------------------------------

class WelcomeScreen extends StatefulWidget {
  const WelcomeScreen({super.key});

  @override
  State<WelcomeScreen> createState() => _WelcomeScreenState();
}

class _WelcomeScreenState extends State<WelcomeScreen> {
  final PageController _pageController = PageController();
  int _currentPage = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Column(
          children: [
            Padding(
              padding: const EdgeInsets.all(32.0),
              child: Text(
                _currentPage == 0 ? 'Sign In' : 'Create Account',
                style: TextStyle(
                    fontSize: 32,
                    fontWeight: FontWeight.bold,
                    color: Colors.indigo.shade700),
              ),
            ),
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 20.0, vertical: 10.0),
              child: Row(
                children: [
                  Expanded(child: _buildAuthTab(context, 'Sign In', 0)),
                  const SizedBox(width: 10),
                  Expanded(child: _buildAuthTab(context, 'Sign Up', 1)),
                ],
              ),
            ),
            Expanded(
              child: PageView(
                controller: _pageController,
                onPageChanged: (index) {
                  setState(() => _currentPage = index);
                },
                children: const [
                  SingleChildScrollView(
                      padding: EdgeInsets.all(20.0),
                      child: LoginForm()),
                  SingleChildScrollView(
                      padding: EdgeInsets.all(20.0),
                      child: SignUpForm()),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildAuthTab(BuildContext context, String title, int pageIndex) {
    final isSelected = _currentPage == pageIndex;
    return InkWell(
      onTap: () {
        _pageController.animateToPage(
          pageIndex,
          duration: const Duration(milliseconds: 300),
          curve: Curves.easeInOut,
        );
      },
      child: Container(
        height: 50,
        alignment: Alignment.center,
        decoration: BoxDecoration(
          color: isSelected ? Colors.indigo : Colors.white,
          borderRadius: BorderRadius.circular(10),
          boxShadow: isSelected
              ? [BoxShadow(color: Colors.indigo.withOpacity(0.5), blurRadius: 5)]
              : [BoxShadow(color: Colors.grey.shade300, blurRadius: 3)],
        ),
        child: Text(
          title,
          style: TextStyle(
            color: isSelected ? Colors.white : Colors.indigo,
            fontWeight: FontWeight.bold,
          ),
        ),
      ),
    );
  }
}

class LoginForm extends StatefulWidget {
  const LoginForm({super.key});

  @override
  State<LoginForm> createState() => _LoginFormState();
}

class _LoginFormState extends State<LoginForm> {
  final _formKey = GlobalKey<FormState>();
  final AuthService _authService = AuthService();
  String _email = '';
  String _password = '';
  String _errorMessage = '';
  bool _isLoading = false;
  bool _showPassword = false;

  void _signIn() async {
    if (_formKey.currentState!.validate()) {
      _formKey.currentState!.save();
      setState(() {
        _isLoading = true;
        _errorMessage = '';
      });

      try {
        await _authService.signIn(email: _email, password: _password);
      } catch (e) {
        setState(() {
          _errorMessage = e.toString();
          _isLoading = false;
        });
      }
    }
  }

  void _signInWithGoogle() async {
    setState(() {
      _isLoading = true;
      _errorMessage = '';
    });
    try {
      await _authService.signInWithGoogle();
    } catch (e) {
      setState(() {
        _errorMessage = e.toString();
      });
    } finally {
      setState(() => _isLoading = false);
    }
  }


  void _sendPasswordReset() async {
    if (_email.isEmpty || !_email.contains('@')) {
      setState(() => _errorMessage = 'Please enter a valid email to reset your password.');
      return;
    }

    setState(() {
      _errorMessage = '';
      _isLoading = true;
    });

    try {
      await _authService.sendPasswordReset(email: _email);
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Password reset link sent to $_email!')),
      );
    } catch (e) {
      setState(() => _errorMessage = e.toString());
    } finally {
      setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Form(
      key: _formKey,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          // Email/Password Fields
          TextFormField(
            keyboardType: TextInputType.emailAddress,
            decoration: const InputDecoration(labelText: 'Email Address'),
            validator: (value) {
              if (value == null || !value.contains('@')) {
                return 'Enter a valid email.';
              }
              return null;
            },
            onSaved: (value) => _email = value!,
            onChanged: (value) => _email = value,
          ),
          const SizedBox(height: 15),
          TextFormField(
            obscureText: !_showPassword,
            decoration: InputDecoration(
              labelText: 'Password',
              suffixIcon: IconButton(
                icon: Icon(
                    _showPassword ? Icons.visibility : Icons.visibility_off),
                onPressed: () {
                  setState(() => _showPassword = !_showPassword);
                },
              ),
            ),
            validator: (value) {
              if (value == null || value.length < 8) {
                return 'Password must be at least 8 characters.';
              }
              return null;
            },
            onSaved: (value) => _password = value!,
          ),
          const SizedBox(height: 10),
          Align(
            alignment: Alignment.centerRight,
            child: TextButton(
              onPressed: _isLoading ? null : _sendPasswordReset,
              child: const Text('Forgot Password?'),
            ),
          ),
          if (_errorMessage.isNotEmpty)
            Padding(
              padding: const EdgeInsets.only(bottom: 15.0),
              child: Text(_errorMessage,
                  style: const TextStyle(color: Colors.red, fontWeight: FontWeight.bold)),
            ),

          // Email/Password Sign In Button
          ElevatedButton(
            onPressed: _isLoading ? null : _signIn,
            child: _isLoading && _email.isNotEmpty && _password.isNotEmpty
                ? const SizedBox(
                height: 20,
                width: 20,
                child: CircularProgressIndicator(
                    color: Colors.white, strokeWidth: 3))
                : const Text('Sign In', style: TextStyle(fontSize: 18)),
          ),

          const SizedBox(height: 20),

          const Center(child: Text("OR", style: TextStyle(color: Colors.grey))),

          const SizedBox(height: 20),

          // Google Sign-In Button
          ElevatedButton.icon(
            icon: Image.network(
              'https://img.icons8.com/color/48/000000/google-logo.png',
              height: 24,
              errorBuilder: (context, error, stackTrace) => const Icon(Icons.g_mobiledata_rounded, color: Colors.indigo, size: 30),
            ),
            label: const Text('Sign In with Google', style: TextStyle(color: Colors.black, fontSize: 18)),
            onPressed: _isLoading ? null : _signInWithGoogle,
            style: ElevatedButton.styleFrom(
              backgroundColor: Colors.white,
              foregroundColor: Colors.indigo.shade600,
              side: BorderSide(color: Colors.grey.shade300),
              elevation: 2,
            ),
          ),
        ],
      ),
    );
  }
}

class SignUpForm extends StatefulWidget {
  const SignUpForm({super.key});

  @override
  State<SignUpForm> createState() => _SignUpFormState();
}

class _SignUpFormState extends State<SignUpForm> {
  final _formKey = GlobalKey<FormState>();
  final AuthService _authService = AuthService();
  String _email = '';
  String _password = '';
  String _errorMessage = '';
  bool _isLoading = false;
  bool _showPassword = false;

  void _signUp() async {
    if (_formKey.currentState!.validate()) {
      _formKey.currentState!.save();
      setState(() {
        _isLoading = true;
        _errorMessage = '';
      });

      try {
        await _authService.signUp(email: _email, password: _password);
      } catch (e) {
        setState(() {
          _errorMessage = e.toString();
          _isLoading = false;
        });
      }
    }
  }

  void _signInWithGoogle() async {
    setState(() {
      _isLoading = true;
      _errorMessage = '';
    });
    try {
      await _authService.signInWithGoogle();
    } catch (e) {
      setState(() {
        _errorMessage = e.toString();
      });
    } finally {
      setState(() => _isLoading = false);
    }
  }


  @override
  Widget build(BuildContext context) {
    return Form(
      key: _formKey,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          // Email/Password Fields
          TextFormField(
            keyboardType: TextInputType.emailAddress,
            decoration: const InputDecoration(labelText: 'Email Address'),
            validator: (value) {
              if (value == null || !value.contains('@')) {
                return 'Enter a valid email.';
              }
              return null;
            },
            onSaved: (value) => _email = value!,
          ),
          const SizedBox(height: 15),
          TextFormField(
            obscureText: !_showPassword,
            decoration: InputDecoration(
              labelText: 'Password (Min 8 Chars)',
              suffixIcon: IconButton(
                icon: Icon(
                    _showPassword ? Icons.visibility : Icons.visibility_off),
                onPressed: () {
                  setState(() => _showPassword = !_showPassword);
                },
              ),
            ),
            validator: (value) {
              if (value == null || value.length < 8) {
                return 'Password must be at least 8 characters.';
              }
              return null;
            },
            onSaved: (value) => _password = value!,
          ),
          const SizedBox(height: 25),

          if (_errorMessage.isNotEmpty)
            Padding(
              padding: const EdgeInsets.only(bottom: 15.0),
              child: Text(_errorMessage,
                  style: const TextStyle(color: Colors.red, fontWeight: FontWeight.bold)),
            ),

          // Email/Password Sign Up Button
          ElevatedButton(
            onPressed: _isLoading ? null : _signUp,
            child: _isLoading
                ? const SizedBox(
                height: 20,
                width: 20,
                child: CircularProgressIndicator(
                    color: Colors.white, strokeWidth: 3))
                : const Text('Sign Up', style: TextStyle(fontSize: 18)),
          ),

          const SizedBox(height: 20),

          const Center(child: Text("OR", style: TextStyle(color: Colors.grey))),

          const SizedBox(height: 20),

          // Google Sign-Up Button
          ElevatedButton.icon(
            icon: Image.network(
              'https://img.icons8.com/color/48/000000/google-logo.png',
              height: 24,
              errorBuilder: (context, error, stackTrace) => const Icon(Icons.g_mobiledata_rounded, color: Colors.indigo, size: 30),
            ),
            label: const Text('Sign Up with Google', style: TextStyle(color: Colors.black, fontSize: 18)),
            onPressed: _isLoading ? null : _signInWithGoogle,
            style: ElevatedButton.styleFrom(
              backgroundColor: Colors.white,
              foregroundColor: Colors.indigo.shade600,
              side: BorderSide(color: Colors.grey.shade300),
              elevation: 2,
            ),
          ),
        ],
      ),
    );
  }
}

// ----------------------------------------------------------------------
// 4. APP STACK SCREEN (Protected)
// ----------------------------------------------------------------------

class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});

  Future<bool> _showSignOutConfirmation(BuildContext context) async {
    return await showDialog<bool>(
      context: context,
      builder: (BuildContext context) {
        return AlertDialog(
          title: const Text('Confirm Sign Out'),
          content: const Text('Are you sure you want to sign out?'),
          actions: <Widget>[
            TextButton(
              onPressed: () => Navigator.of(context).pop(false),
              child: const Text('Cancel'),
            ),
            TextButton(
              onPressed: () => Navigator.of(context).pop(true),
              child: const Text('Sign Out', style: TextStyle(color: Colors.red)),
            ),
          ],
        );
      },
    ) ?? false;
  }

  @override
  Widget build(BuildContext context) {
    final user = FirebaseAuth.instance.currentUser;
    final AuthService authService = AuthService();

    return Scaffold(
      appBar: AppBar(
        title: const Text('Dashboard (Protected)', style: TextStyle(color: Colors.white)),
        backgroundColor: Colors.indigo.shade700,
        iconTheme: const IconThemeData(color: Colors.white),
        actions: [
          IconButton(
            icon: const Icon(Icons.logout),
            onPressed: () async {
              final confirmed = await _showSignOutConfirmation(context);
              if (confirmed) {
                await authService.signOut();
              }
            },
          ),
        ],
      ),
      body: Center(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(20.0),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: <Widget>[
              Icon(Icons.lock_open_rounded, size: 80, color: Colors.indigo.shade500),
              const SizedBox(height: 20),
              const Text(
                'Welcome Home!',
                style: TextStyle(fontSize: 28, fontWeight: FontWeight.bold, color: Color(0xFF303F9F)),
                textAlign: TextAlign.center,
              ),
              const Text(
                'Your session is successfully authenticated and protected.',
                style: TextStyle(fontSize: 16, color: Colors.grey),
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: 30),
              _buildProfileCard(user),
              const SizedBox(height: 50),
              ElevatedButton.icon(
                icon: const Icon(Icons.logout_rounded),
                label: const Text('Sign Out', style: TextStyle(fontSize: 18)),
                onPressed: () async {
                  final confirmed = await _showSignOutConfirmation(context);
                  if (confirmed) {
                    await authService.signOut();
                  }
                },
                style: ElevatedButton.styleFrom(
                  backgroundColor: Colors.redAccent,
                  minimumSize: const Size(200, 50),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildProfileCard(User? user) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: Colors.indigo.shade50,
        borderRadius: BorderRadius.circular(15),
        border: Border.all(color: Colors.indigo.shade100, width: 2),
        boxShadow: [
          BoxShadow(
            color: Colors.indigo.withOpacity(0.1),
            spreadRadius: 2,
            blurRadius: 5,
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text('User Details', style: TextStyle(fontSize: 20, fontWeight: FontWeight.w700, color: Colors.indigo.shade800)),
          const Divider(height: 20, thickness: 1.5, color: Colors.indigo),
          _buildProfileRow(Icons.mail_outline, 'Email:', user?.email ?? 'N/A'),
          _buildProfileRow(Icons.tag, 'UID:', user?.uid ?? 'N/A'),
          _buildProfileRow(Icons.verified_user_sharp, 'Status:', user?.emailVerified == true ? 'Verified' : 'Unverified'),
          if (user?.metadata != null)
            _buildProfileRow(Icons.access_time, 'Created:', user!.metadata.creationTime?.toLocal().toString().split('.')[0] ?? 'N/A'),
        ],
      ),
    );
  }

  Widget _buildProfileRow(IconData icon, String label, String value) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 8.0),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Icon(icon, size: 20, color: Colors.indigo),
          const SizedBox(width: 10),
          Text(label, style: const TextStyle(fontWeight: FontWeight.w600)),
          const SizedBox(width: 8),
          Expanded(child: Text(value, style: const TextStyle(fontFamily: 'monospace', fontSize: 14))),
        ],
      ),
    );
  }
}
