// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVh1Atc9dLIZCFwOgtKm7GNAiG-kUaL0g',
    appId: '1:33253746777:web:09797dcf9cde929f4ae948',
    messagingSenderId: '33253746777',
    projectId: 'cloudcal-a826f',
    authDomain: 'cloudcal-a826f.firebaseapp.com',
    storageBucket: 'cloudcal-a826f.firebasestorage.app',
    measurementId: 'G-E4079EB74P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKenOKzGYgJqXYYUrSAlPz_DcajqLxqQw',
    appId: '1:33253746777:android:fc4fa562f64c6c3a4ae948',
    messagingSenderId: '33253746777',
    projectId: 'cloudcal-a826f',
    storageBucket: 'cloudcal-a826f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_PkxcWuReJCi6kb2uYtGs_NFdddpYONE',
    appId: '1:33253746777:ios:da016470bd6bc4af4ae948',
    messagingSenderId: '33253746777',
    projectId: 'cloudcal-a826f',
    storageBucket: 'cloudcal-a826f.firebasestorage.app',
    iosBundleId: 'com.example.firecal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_PkxcWuReJCi6kb2uYtGs_NFdddpYONE',
    appId: '1:33253746777:ios:da016470bd6bc4af4ae948',
    messagingSenderId: '33253746777',
    projectId: 'cloudcal-a826f',
    storageBucket: 'cloudcal-a826f.firebasestorage.app',
    iosBundleId: 'com.example.firecal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVh1Atc9dLIZCFwOgtKm7GNAiG-kUaL0g',
    appId: '1:33253746777:web:4c342361bf24bd494ae948',
    messagingSenderId: '33253746777',
    projectId: 'cloudcal-a826f',
    authDomain: 'cloudcal-a826f.firebaseapp.com',
    storageBucket: 'cloudcal-a826f.firebasestorage.app',
    measurementId: 'G-9LBQBH0YD2',
  );

}